apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:gJfYIELbSBQIFiw4NUMJoJtQoLtqgJkNm0Gpbs4mCFmkfvXGmT9Ejw==,iv:gnicsYrLad9Uad71/8xpNRS8CkZSrdkmZHhc6V/tsXY=,tag:AqdZhcPcp1QggWsRscifUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1erlmnukvaa4uk5ufgr5ktk5jk80rm23ze8vhdsd2e3cvrzf0ecpqjcn9g9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYnFrM3kxSXV5QTZ5cXhj
            MlErZUhOWGlwZnc5eFpWcHl3N0JxT1BnU0ZNCkp1RXJZenlkMDdUYk5qOUsweFVS
            T1ZFbktxdkNTN0hxbUdZTjNpV1FUNkEKLS0tIGwxTXhqdE5uUEpHcWJyNGxpLzdv
            NUNYaWtYYUxmUTYwWGYwWUx2elFXalUKIh5KulZ/CbKOBp4cunICJ4Z5DNXutZdg
            Lk51wtgYpZWwZ29/r6zOQUjPu8rhRAzOLe/jR8FIrPa1XLSSgFE9HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-31T18:33:50Z"
    mac: ENC[AES256_GCM,data:qKUqRhrGxao0MLBFQcRjQ4bJziKXPX8kVAeFvBSznS4Ro83lpewwAYEy8uY8yHzZSFMMKeMM5Kpm1QKq9Hxcw3xS3/vKhlf3BRe2jUeoY59sepYoHV9z50uYCjkZiskke/Bh6y6pUULkOblgHwkI8yHHpFiYR5vDVgEFhi/Cr38=,iv:1VtRjh51J/KBeh8i3L+72KBdS3oMo5yhodiv+auVp8o=,tag:vJ8zXWOINtXlGpGAgZa/9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
